[package]
name = "day2"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "^0.8"

[[bin]]
name = "day2-part1"
path = "src/day2-part1.rs"

[[bin]]
name = "day2-part2"
path = "src/day2-part2.rs"
